export default `&emsp;I was born in <a target="_blank" href="https://en.wikipedia.org/wiki/Donetsk">Donetsk</a>, Ukraine in September 1995. I am the eldest and my brother is two years younger. I grew up in a post-Soviet middle-class family.  My father, Alexander, has an engineering education and works as a car mechanic. Mother, Ludmila, has an engineer technologist profession.
<br>&emsp;When I was 7 years old I went to elementary school <a target="_blank" href="https://vk.com/club79804679">№148</a> in Donetsk city. After completing 9 classes I moved to <a target="_blank" href="https://vk.com/albums-111724596">the Donetsk Technical Lyceum</a>, during two years of study at the Lyceum, I did one’s best in the study of programming, physics and mathematics. I took an active part in the work of the <a target="_blank" href="https://en.wikipedia.org/wiki/Minor_Academy_of_Sciences_of_Ukraine">Minor Science Academy of Ukraine</a> in the information technology section, working on the creation of an Optical Text Recognition system.
<br>&emsp;In 2013, I successfully passed the entrance exams and entered <a target="_blank" href="https://en.wikipedia.org/wiki/Donetsk_National_Technical_University">the Donetsk National Technical University</a> on the profile “Electronic devices and systems”.
<br>&emsp;On August, 2014, I moved to <a target="_blank" href="https://en.wikipedia.org/wiki/Kursk">Kursk</a>, Russia.  ► In January 2015, I was enrolled in <a target="_blank" href="http://en.swsu.ru/">the South-West State University</a>  for the “Computer Science and Computing Engineering” program.
<br>&emsp;In parallel with studying, from October  2015 to October  2017, I worked at the Small Satellites Development Center (Scientific Research Institute of Radioelectronic Systems). I participated in the development and creation of 5 small satellites.
<br>&emsp;Since 2015 I have been active in social activities in <a target="_blank" href="https://sporadic.ru/">the Kursk Regional Youth Sports Public Organization “SPORADIK” (Radio Club RW3WWW)</a> . In December 2016, I received official Russian citizenship. In 2017 I defended a bachelor's degree on the topic “Control system of a radio transmitting device for a small satellite”.
<br>&emsp;In 2017 I entered the South-West State University for the master's program of the same specialty. In parallel with studying, I carried out work under contracts. Of the significant projects, I developed a web-site for distance learning programming <a target="_blank" href="http://swiftbook.ru/">swiftbook.ru</a>, carried out work under the theme “Conducting research and development work on the development and creation of Ecuador-UTE nanosatellite RS16S.
<br>&emsp;In July 2019, I took a master's degree in computer science. And moved to  <a target="_blank" href="https://es.wikipedia.org/wiki/Quito">Quito</a>, Ecuador. I work as a teacher-researcher at the center of robotics at <a target="_blank" href="https://www.uce.edu.ec/"></a> the Central University of Ecuador till December 2020. At the university, I led the development of systems with drones, robots and medical equipment. At the same time, I worked part-time for a <a target="_blank" href="https://fuelup.ru/"> FuelUp</a> company as a DevOps and worked for <a target="_blank" href="https://getpayever.com/">Payever company</a> from Germany.
<br>&emsp;Since December 2020, I have been working remotely for a company called <a target="_blank" href="https://preciouspayload.com/"> PreciousPayload</a>, an organization that launches satellites into space.
<br>&emsp;A year later, I changed my job and began working in an Ecuadorian office at <a target="_blank" href="https://workersbenefitfund.com/"> Workers Benefits Found</a> company. This company works with trade unions in the United States and protects the rights of gig workers.
<br>&emsp;life will show what lies ahead for me<a target="_blank" href="https://en.wikipedia.org/wiki/Chronology_of_the_universe">...</a>
`;


