export interface IProject {
  name: string,
  description: string,
  link: string,
  imgUrl: string,
  tags: ProjectTag[],
  points: number
}
export enum ProjectTag {
  All,
  Website,
  Desktop,
  Mobile,
  Engineer,
  Social
}
export default [
  {
    tags: [ProjectTag.Website, ProjectTag.Social],
    link: "http://sporadic.ru/",
    description: "A site to my students club. It powered by WordPress. I also provide technical support. The project gave me the experience of an administrator, content manager and designer.",
    imgUrl: "assets/images/projects/sporadic",
    name: "SPORADIC",
    points: 6,
  },
  {
    tags: [ProjectTag.Desktop],
    link: null,
    description: "Desktop version of Optimum Beauty's consolidated price programs for Velox LLC. The startup closed in 2016 but it gave me a good experience in communicating with retail clients.",
    imgUrl: "assets/images/projects/optimum.jpg",
    name: "Optimum Beauty",
    points: 0,
  },
  {
    tags: [ProjectTag.Mobile],
    link: "http://runlimit.com",
    description: "An application to pick the size of a motorcycle helmet using recognition.\nDevelopment of a mobile application. The project improved my API design skills and allowed me to learn Kotlin",
    imgUrl: "assets/images/projects/runlimit.jpg",
    name: "RUNLIMIT",
    points: 0,
  },
  {
    tags: [ProjectTag.Website],
    link: "https://swiftbook.ru",
    description: "My first full-time project. Education portal powered by Wordpress, migration from Drupal, writing plugins, themes and supports. I improved my PHP, SQL and WordPress skills.",
    imgUrl: "assets/images/projects/swiftbook",
    name: "SwiftBook",
    points: 5,
  },
  {
    tags: [ProjectTag.Engineer],
    link: "https://amsat-uk.org/2017/06/30/russian-tanusha-1-and-2-satellites/",
    description: "Two Russian satellites launched from the International Space Station. It's my first true engineering project. Working with electrical circuits, programming AVR microcontrollers, and working with electronic communication devices.",
    imgUrl: "assets/images/projects/tanusha-swsu",
    name: "CubeSats Tanusha 1 & 2",
    points: 3,
  },
  {
    tags: [ProjectTag.Engineer],
    link: "https://www.youtube.com/watch?v=FUMADz-zyj8",
    description: "International satellite project. I improved my engineering and programming skills in particular compression algorithms, and noise-correcting coding. Gave me the opportunity to move to Ecuador in the future.",
    imgUrl: "assets/images/projects/eq.jpg",
    name: "Ecuador UTE-SWSU RS3S",
    points: 0,
  },
  {
    tags: [ProjectTag.Engineer],
    link: null,
    description: " ",
    imgUrl: "assets/images/projects/tpu.JPG",
    name: "Tomsk-TPU-120",
    points: 0,
  },
  {
    tags: [ProjectTag.Mobile],
    link: null,
    description: "Android app for live cards with NFC",
    imgUrl: "assets/images/projects/a3.jpg",
    name: "iMatreshka",
    points: 0,
  },
  {
    tags: [ProjectTag.Social],
    link: "https://hack-kursk.ru/",
    description: "Organizing and conducting a 3 competition for 100 programmers in 2017,2018 and 2019.",
    imgUrl: "assets/images/projects/work_8.webp",
    name: "Hack-Kursk \"IT Vocation\"",
    points: 0,
  },
  {
    tags: [ProjectTag.Website],
    link: "#",
    description: " ",
    imgUrl: "assets/images/projects/programmers.jpg",
    name: " PixelBook.ru",
    points: 0,
  },
  {
    tags: [ProjectTag.Website],
    link: "#",
    description: "My first website experience on php, bootstrap, jQuery and ajax.",
    imgUrl: "assets/images/projects/dobriedela.webp",
    name: "Dobrie dela",
    points: 0,
  },
  {
    tags: [ProjectTag.Mobile],
    link: "https://fuelup.ru/",
    description: "Contactless car refueling system. I administered a microservice system. Became DevOps. A lot of nervous work. hahaha",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "FuelUP",
    points: 0,
  },
  {
    tags: [ProjectTag.Mobile],
    link: "https://fuelup.ru/",
    description: "Infrastructure development and administration",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "FuelUP",
    points: 0,
  },
  {
    tags: [ProjectTag.Social],
    link: 'https://sporadic.ru/%d1%80%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5-%d1%82%d0%b5%d1%85%d0%bd%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b3%d1%80%d0%b0%d0%bc%d0%be%d1%82%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d0%b8-%d1%82/',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "Course \"Basics of circuitry\"",
    points: 0,
  },
  {
    tags: [ProjectTag.Social],
    link: 'https://sporadic.ru/%d1%80%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5-%d1%82%d0%b5%d1%85%d0%bd%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b3%d1%80%d0%b0%d0%bc%d0%be%d1%82%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d0%b8-%d1%82/',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "UCE Drones",
    points: 0,
  },
  {
    tags: [ProjectTag.Social],
    link: 'https://sporadic.ru/%d1%80%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5-%d1%82%d0%b5%d1%85%d0%bd%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b3%d1%80%d0%b0%d0%bc%d0%be%d1%82%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d0%b8-%d1%82/',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "UTE Respirator artisicial",
    points: 0,
  },
  {
    tags: [ProjectTag.Social],
    link: 'https://sporadic.ru/%d1%80%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5-%d1%82%d0%b5%d1%85%d0%bd%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b9-%d0%b3%d1%80%d0%b0%d0%bc%d0%be%d1%82%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d0%b8-%d1%82/',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "UCE Cource ",
  },
  {
    tags: [ProjectTag.Social],
    link: ' ',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "facebook ads rs pr",
    points: 0,
  },
  {
    tags: [ProjectTag.Website],
    link: 'https://getpayever.com/',
    description: "Online website builder. Significantly increased my level of Angular mastered rxjs. The company had well-established testing and deployment processes.",
    imgUrl: "assets/images/projects/payever",
    name: "PayEver",
    points: 2,
  },
  {
    tags: [ProjectTag.Website],
    link: 'https://preciouspayload.com/',
    description: "The platform for booking cells on rockets for a satellite and the exchange of documentation at different stages of the project. I improved my Angular, NgRX, learned Spring, and gained experience in organizing good dev processes.",
    imgUrl: "assets/images/projects/precious_payload",
    name: "Precious Payload",
    points: 1,
  },
  {
    tags: [ProjectTag.Social],
    link: ' ',
    description: "Development of a training program for a course \"Basics of circuitry\" for young people interested in electronics. Improved my teaching and communication skills.",
    imgUrl: "assets/images/projects/fuelup.png",
    name: "WBF System core",
    points: 0,
  },
  {
    tags: [ProjectTag.Mobile],
    link: '',
    description: "",
    imgUrl: "assets/images/projects/",
    name: "WBF Driver 360",
    points: 0,
  }

] as IProject[];

